### ISSUE TITLE
Error when reconnecting

### ISSUE THREAD

**Issue by lhz516** [Micjoyce/wechat-mina-ddp#1]
当server断开重连后，出现这个error，并且每发送任何DDP message都会出现这个error，同时多接受一次message（console每行最左边显示数量都是2）。
![_20161113181725](https://cloud.githubusercontent.com/assets/9879279/20251355/78f3ea1c-a9cd-11e6-80da-66e609fe9322.png)
我已经分别试过设置autoConnect为true和false然后手动重连都会出现这个症状

**Comment by Micjoyce** [comment]
建立了多个ddp连接，我找个时间排查一下，而且有一个问题就是重新连接calls为空，导致报错，这个只需要增加一个判断即可。

**Comment by lhz516** [comment]
最近正好在用这个做项目，就fix了，已提交PR。原因是`wx.onSocketXXX`这些在每次重连时又会再运行一次，确保这些只在创建对象时运行一次就好了，并且`'callback' of undefined`的问题也没有了

**Comment by Micjoyce** [comment]
谢谢哈
